# Generated by Django 5.1.4 on 2024-12-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default='default_images/default_picture.png', null=True, upload_to='post_pictures/', verbose_name='picture')),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('custom_input_1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_input_2', models.CharField(blank=True, max_length=255, null=True)),
                ('prefer', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
