# Generated by Django 5.1.4 on 2024-12-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
